version: '3.4'

x-healthcheck-defaults: &default-healthchecks
  interval: 30s
  timeout: 10s
  retries: 3

x-nx-volumes: &nx-volumes
  - ./:/usr/app
  - /usr/app/node_modules
  - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
  - ./mongodb/data:/data/db

services:
  database:
    image: mongo:4.4.1
    environment:
      - MONGO_INITDB_DATABASE=/run/secrets/db_name
      - MONGO_INITDB_ROOT_USERNAME=/run/secrets/db_root_username
      - MONGO_INITDB_ROOT_PASSWORD=/run/secrets/db_root_password
    volumes: *nx-volumes
    ports:
      - '27017-27019:27017-27019'
    secrets:
      - db_name
      - db_root_username
      - db_root_password

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        PORT: 3333
    command: yarn serve:api
    volumes: *nx-volumes
    ports:
      - '3333:3333'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3333']
      <<: *default-healthchecks

  app:
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        PORT: 4200
    command: yarn serve:web
    volumes: *nx-volumes
    ports:
      - '4200:4200'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4200']
      <<: *default-healthchecks

secrets:
  db_name:
    file: mongodb/db_name.txt
  db_root_username:
    file: mongodb/db_root_username.txt
  db_root_password:
    file: mongodb/db_root_password.txt
